### ISSUE TITLE
show: Machines aren't ordered correctly

### ISSUE THREAD

**Issue by dlespiau** [weaveworks/footloose#111]
I would expect node0 to be first, node1 second

```
$ footloose show -o json
{
  "machines": [
    {
      "name": "/cluster-node1",
      "state": "Stopped",
      "ports": [
        {
          "guest": 22,
          "host": 33031
        }
      ],
      "hostname": "node1",
      "image": "quay.io/footloose/centos7:latest",
      "cmd": "/sbin/init"
    },
    {
      "name": "/cluster-node0",
      "state": "Stopped",
      "ports": [
        {
          "guest": 22,
          "host": 33030
        }
      ],
      "hostname": "node0",
      "image": "quay.io/footloose/centos7:latest",
      "cmd": "/sbin/init"
    }
  ]
}
```

**Comment by Skarlso** [comment]
@dlespiau What should they be ordered by? Hostname and name as fallback? Or just name? :)

**Comment by dlespiau** [comment]
Thinking about it, it's not that obvious. You may have noticed that, in the configuration, `machines` is an array. That's because the user can do something like:

```
cluster:
  name: cluster
  privateKey: cluster-key
machines:
- count: 3
  spec:
    image: quay.io/footloose/centos7:latest
    name: control-plane-%d
    portMappings:
    - containerPort: 22
- count: 3
  spec:
    image: quay.io/footloose/centos7:latest
    name: worker-%d
    portMappings:
    - containerPort: 22
```

```
$ footloose create
INFO[0000] Image: quay.io/footloose/centos7:latest present locally 
INFO[0000] Image: quay.io/footloose/centos7:latest present locally 
INFO[0000] Creating machine: cluster-control-plane-0 ... 
INFO[0000] Creating machine: cluster-control-plane-1 ... 
INFO[0001] Creating machine: cluster-control-plane-2 ... 
INFO[0001] Creating machine: cluster-worker-0 ...       
INFO[0002] Creating machine: cluster-worker-1 ...       
INFO[0003] Creating machine: cluster-worker-2 ...       
```

I think the order should be the same as the one defined in the config file so, in that case:

```
cluster-control-plane-0
cluster-control-plane-1
cluster-control-plane-2
cluster-worker-0
cluster-worker-1
cluster-worker-2
```

Interesting, the comparison would have to respect natural numbers in the strings. ie.

**Bad**:
```
foo-1
foo-10
foo-11
foo-2
...
foo-9
```

**Good**:

```
foo-1
foo-2
...
foo-9
foo-10
foo-11
```
```
