### ISSUE TITLE
ubuntu16.04: Freezing execution on mac

### ISSUE THREAD

**Issue by kongslund** [weaveworks/footloose#124]
I am unable to successfully start `quay.io/footloose/ubuntu16.04:(0.3.0|latest)` on my Mac using Docker Desktop Community 2.0.0.3 (Engine 18.09.2). For comparison, it works just fine when using `quay.io/footloose/centos7:0.3.0`.

```
$ footloose create
INFO[0000] Image: quay.io/footloose/ubuntu16.04:latest present locally
INFO[0000] Creating machine: cluster-node0 ...
$ docker logs cluster-node0
Failed to determine whether /sys is a mount point: Operation not permitted
Failed to determine whether /proc is a mount point: Operation not permitted
Failed to determine whether /dev is a mount point: Operation not permitted
Failed to determine whether /dev/shm is a mount point: Operation not permitted
Failed to determine whether /run is a mount point: Operation not permitted
Failed to determine whether /run/lock is a mount point: Operation not permitted
Failed to determine whether /sys/fs/cgroup is a mount point: Operation not permitted
Failed to determine whether /sys/fs/cgroup/systemd is a mount point: Operation not permitted
[!!!!!!] Failed to mount API filesystems, freezing.
Freezing execution.
```

My `footloose.yaml`:

```
cluster:
  name: cluster
  privateKey: cluster-key
machines:
- count: 1
  spec:
    image: quay.io/footloose/ubuntu16.04:latest
    name: node%d
    portMappings:
    - containerPort: 22
```

**Comment by dlespiau** [comment]
Hello Jonas! Thanks for trying `footloose` and taking the time to file that bug report. I don't have a machine with macOS myself, but hopefully someone using mac can have a look.

**Comment by Skarlso** [comment]
@kongslund @dlespiau I'll take a look. I'm on a mac and 16.04 is my baby. :D

**Comment by Skarlso** [comment]
@kongslund Ah! It's a subtle issue, but you are missing `privileged: true` from your config file. :)

**Comment by Skarlso** [comment]
```
~/goprojects/footloose master*
❯ ./footloose create
INFO[0000] Image: docker.io/skarlso/footloose:ubuntu16 present locally
INFO[0000] Creating machine: cluster-node0 ...

~/goprojects/footloose master*
❯ docker logs cluster-node0
Failed to insert module 'autofs4': No such file or directory
systemd 229 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN)
Detected virtualization docker.
Detected architecture x86-64.

Welcome to Ubuntu 16.04.5 LTS!

Set hostname to <node0>.
[  OK  ] Reached target Swap.
[  OK  ] Listening on Journal Audit Socket.
[  OK  ] Listening on Journal Socket (/dev/log).
[  OK  ] Reached target Paths.
[  OK  ] Reached target Local File Systems.
[  OK  ] Listening on Journal Socket.
[  OK  ] Reached target Sockets.
[  OK  ] Created slice System Slice.
         Starting Journal Service...
[  OK  ] Reached target Slices.
         Starting Create Static Device Nodes in /dev...
[  OK  ] Started Create Static Device Nodes in /dev.
[  OK  ] Started Journal Service.
[  OK  ] Reached target System Initialization.
[  OK  ] Started Daily Cleanup of Temporary Directories.
[  OK  ] Reached target Timers.
[  OK  ] Reached target Basic System.
         Starting Permit User Sessions...
         Starting LSB: Set the CPU Frequency Scaling governor to "ondemand"...
         Starting /etc/rc.local Compatibility...
         Starting OpenBSD Secure Shell server...
[  OK  ] Started Permit User Sessions.
[  OK  ] Started /etc/rc.local Compatibility.
[  OK  ] Started OpenBSD Secure Shell server.
[  OK  ] Started LSB: Set the CPU Frequency Scaling governor to "ondemand".
[  OK  ] Reached target Multi-User System.
```

**Comment by Skarlso** [comment]
Footloose file:
```
❯ cat footloose.yaml
cluster:
  name: cluster
  privateKey: cluster-key
machines:
- count: 1
  spec:
    image: docker.io/skarlso/footloose:ubuntu16
    name: node%d
    portMappings:
    - containerPort: 22
    privileged: true
```
