### ISSUE TITLE
hostPort offsetting confusing when multiple machines

### ISSUE THREAD

**Issue by kke** [weaveworks/footloose#240]
A config such as:

```
machines:
- count: 1
  backend: docker
  spec:
    portMappings:
    - containerPort: 22
      hostPort: 9022
- count: 1
  backend: docker
  spec:
    portMappings:
    - containerPort: 22
      hostPort: 9122
```

will make the second machine's SSH port 9123.

I believe this is because there's something like `hostPort + %d` where `%d` is the machine number. But for a scenario like this it is pretty confusing.
